import { AffiliateProduct } from './types';

// Sample affiliate products - replace with actual affiliate links
export const AFFILIATE_PRODUCTS: AffiliateProduct[] = [
  {
    id: '1',
    name: 'Eco-Friendly All-Purpose Cleaner Set',
    description: 'Plant-based, non-toxic cleaning solution safe for all surfaces. Perfect for homes with kids and pets.',
    price: 34.99,
    affiliateLink: 'https://amazon.com/example-product', // Replace with actual Amazon Associates link
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400',
    category: 'Cleaning Solutions',
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Professional Microfiber Cloth Set (24 Pack)',
    description: 'Ultra-absorbent microfiber cloths for streak-free cleaning. Machine washable and reusable.',
    price: 19.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400',
    category: 'Cleaning Tools',
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Cordless Vacuum Cleaner',
    description: 'Powerful suction with up to 60 minutes runtime. Perfect for quick clean-ups and pet hair.',
    price: 249.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400',
    category: 'Vacuum Cleaners',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Steam Mop for Hard Floors',
    description: 'Chemical-free cleaning with the power of steam. Kills 99.9% of germs and bacteria.',
    price: 89.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=400',
    category: 'Floor Care',
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Natural Dish Soap - Grove Collaborative',
    description: 'Biodegradable formula that cuts through grease. Gentle on hands, tough on messes.',
    price: 12.99,
    affiliateLink: 'https://grove.co/example-product', // Grove Collaborative affiliate link
    imageUrl: 'https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=400',
    category: 'Kitchen Cleaning',
    rating: 4.8,
  },
  {
    id: '6',
    name: 'Toilet Bowl Cleaner Wand',
    description: 'Disposable cleaning heads with built-in cleaner. No more dirty toilet brushes.',
    price: 24.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400',
    category: 'Bathroom Cleaning',
    rating: 4.7,
  },
  {
    id: '7',
    name: 'Robot Vacuum - iRobot',
    description: 'Smart navigation and app control. Automatically empties itself for weeks of hands-free cleaning.',
    price: 599.99,
    affiliateLink: 'https://example.com/irobot', // iRobot affiliate link
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400',
    category: 'Robot Vacuums',
    rating: 4.9,
  },
  {
    id: '8',
    name: 'Carpet Spot Cleaner Machine',
    description: 'Portable and powerful for spot cleaning carpets, upholstery, and car interiors.',
    price: 129.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1584622781867-1c8857e20f50?w=400',
    category: 'Carpet Care',
    rating: 4.6,
  },
  {
    id: '9',
    name: 'Window Squeegee Pro Set',
    description: 'Professional-grade squeegee with extension pole for streak-free windows.',
    price: 34.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=400',
    category: 'Window Cleaning',
    rating: 4.5,
  },
  {
    id: '10',
    name: 'Natural Wood Floor Cleaner',
    description: 'pH-balanced formula specifically designed for hardwood floors. Leaves no residue.',
    price: 15.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=400',
    category: 'Floor Care',
    rating: 4.7,
  },
  {
    id: '11',
    name: 'Odor Eliminating Spray - Eco Nuts',
    description: 'Natural enzyme-based odor eliminator. Safe for fabrics, carpets, and air.',
    price: 18.99,
    affiliateLink: 'https://example.com/econuts', // Eco Nuts affiliate link
    imageUrl: 'https://images.unsplash.com/photo-1629191995951-87b60115eb27?w=400',
    category: 'Air Fresheners',
    rating: 4.8,
  },
  {
    id: '12',
    name: 'Cleaning Caddy Organizer',
    description: 'Portable caddy keeps all your cleaning supplies organized and easy to carry.',
    price: 22.99,
    affiliateLink: 'https://amazon.com/example-product',
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400',
    category: 'Organization',
    rating: 4.6,
  },
];

export const PRODUCT_CATEGORIES = [
  'All Products',
  'Cleaning Solutions',
  'Cleaning Tools',
  'Vacuum Cleaners',
  'Floor Care',
  'Kitchen Cleaning',
  'Bathroom Cleaning',
  'Carpet Care',
  'Window Cleaning',
  'Organization',
];
