import { DirectoryListing } from './types';

// Sample directory listings - In production, this would come from a database
export const DIRECTORY_LISTINGS: DirectoryListing[] = [
  {
    id: '1',
    companyName: 'Sparkle Clean Pro',
    description: 'Professional residential and commercial cleaning services with eco-friendly products. 15 years of experience serving the community.',
    rating: 4.8,
    reviewCount: 127,
    serviceArea: ['Ann Arbor', 'Ypsilanti', 'Saline'],
    services: ['House Cleaning', 'Deep Cleaning', 'Office Cleaning', 'Move In/Out'],
    verified: true,
    isPaid: true,
    phoneNumber: '(734) 555-0101',
    website: 'https://sparklecleanpro.example.com',
    featured: true,
    socialMedia: {
      facebook: 'https://facebook.com/sparklecleanpro',
      instagram: 'https://instagram.com/sparklecleanpro',
    },
  },
  {
    id: '2',
    companyName: 'Green Earth Cleaning',
    description: 'Certified green cleaning service using 100% organic, non-toxic products. Perfect for families with children and pets.',
    rating: 4.9,
    reviewCount: 203,
    serviceArea: ['Ann Arbor', 'Dexter', 'Chelsea'],
    services: ['Residential Cleaning', 'Green Cleaning', 'Disinfection', 'Carpet Cleaning'],
    verified: true,
    isPaid: true,
    phoneNumber: '(734) 555-0102',
    website: 'https://greenearthcleaning.example.com',
    featured: true,
  },
  {
    id: '3',
    companyName: 'A2 Office Cleaners',
    description: 'Specializing in commercial cleaning for offices, medical facilities, and retail spaces. Available 24/7.',
    rating: 4.7,
    reviewCount: 89,
    serviceArea: ['Ann Arbor', 'Ypsilanti'],
    services: ['Office Cleaning', 'Medical Office Cleaning', 'Retail Cleaning', 'Post-Construction'],
    verified: true,
    isPaid: true,
    phoneNumber: '(734) 555-0103',
    website: 'https://a2officecleaners.example.com',
    featured: false,
  },
  {
    id: '4',
    companyName: 'Perfect Touch Cleaning',
    description: 'Family-owned cleaning business providing personalized service with attention to detail.',
    rating: 4.6,
    reviewCount: 56,
    serviceArea: ['Ann Arbor', 'Saline'],
    services: ['House Cleaning', 'Deep Cleaning', 'Window Cleaning'],
    verified: true,
    isPaid: false,
  },
  {
    id: '5',
    companyName: 'Elite Commercial Services',
    description: 'Large-scale commercial cleaning for businesses, warehouses, and industrial facilities.',
    rating: 4.5,
    reviewCount: 134,
    serviceArea: ['Ann Arbor', 'Ypsilanti', 'Pittsfield'],
    services: ['Commercial Cleaning', 'Warehouse Cleaning', 'Pressure Washing', 'Air Duct Cleaning'],
    verified: true,
    isPaid: true,
    phoneNumber: '(734) 555-0105',
    website: 'https://elitecommercial.example.com',
    featured: false,
  },
  {
    id: '6',
    companyName: 'Fresh Start Cleaning Co',
    description: 'Affordable cleaning services for students and young professionals. Flexible scheduling.',
    rating: 4.4,
    reviewCount: 78,
    serviceArea: ['Ann Arbor', 'Ypsilanti'],
    services: ['Apartment Cleaning', 'Move In/Out', 'Basic Cleaning'],
    verified: true,
    isPaid: false,
  },
  {
    id: '7',
    companyName: 'Precision Carpet Care',
    description: 'Specialized carpet and upholstery cleaning using advanced steam cleaning technology.',
    rating: 4.9,
    reviewCount: 167,
    serviceArea: ['Ann Arbor', 'Dexter', 'Chelsea', 'Saline'],
    services: ['Carpet Cleaning', 'Upholstery Cleaning', 'Stain Removal'],
    verified: true,
    isPaid: true,
    phoneNumber: '(734) 555-0107',
    website: 'https://precisioncarpet.example.com',
    featured: true,
  },
  {
    id: '8',
    companyName: 'Maid to Perfection',
    description: 'Experienced cleaning professionals providing consistent, high-quality residential cleaning.',
    rating: 4.7,
    reviewCount: 145,
    serviceArea: ['Ann Arbor', 'Ypsilanti', 'Saline'],
    services: ['House Cleaning', 'Deep Cleaning', 'Move In/Out', 'Post-Construction'],
    verified: true,
    isPaid: false,
  },
];
